name: rol_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  file_picker: ^4.0.0
  path_provider:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/Logo.png
    - assets/music/
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura_font.ttf
